services:
  tipsetc-app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery-worker:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: celery -A tipsetc worker --loglevel=INFO
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/vaf/lib/postgresql/data/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  flower:
    image: mher/flower
    command: celery flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  db:
