# Generated by Django 5.2.1 on 2025-05-21 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="posts",
        ),
    ]
