# Generated by Django 5.2.1 on 2025-05-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_tag_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("for_subscribers", "Published for subscribers"),
                    ("for_all", "Published for All"),
                ],
                max_length=16,
            ),
        ),
    ]
