# Generated by Django 5.2.1 on 2025-05-22 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_tag_created_at_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="timestamp",
        ),
    ]
