# Generated by Django 5.2.1 on 2025-05-22 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_remove_post_timestamp"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userprofile",
            table="user_profiles",
        ),
    ]
