# Generated by Django 5.2.1 on 2025-05-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
