# Generated by Django 5.2.1 on 2025-07-06 22:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.CreateModel(
            name='PostRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_rating', to='blog.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posts_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_rating',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
