# Generated by Django 5.2.1 on 2025-07-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_postrating_post_alter_postrating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
