"""empty message

Revision ID: 1f5f51afa37e
Revises: 42acb0cca580
Create Date: 2022-06-13 13:17:56.074164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5f51afa37e'
down_revision = '42acb0cca580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posttag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posttag',
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('teg_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['teg_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###
