"""empty message

Revision ID: 371c81ea5e71
Revises: 9bf7e368b144
Create Date: 2022-05-17 01:09:33.056696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371c81ea5e71'
down_revision = '9bf7e368b144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
