"""empty message

Revision ID: 42acb0cca580
Revises: 13a1d80285bd
Create Date: 2022-06-11 15:27:51.054808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42acb0cca580'
down_revision = '13a1d80285bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posttag',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('teg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['teg_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posttag')
    # ### end Alembic commands ###
