"""empty message

Revision ID: 71d20e7f64fa
Revises: f28de64b08ff
Create Date: 2022-05-16 00:42:22.482368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d20e7f64fa'
down_revision = 'f28de64b08ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
