"""empty message

Revision ID: 7f6215cc7c36
Revises: dc4e168b2618
Create Date: 2022-02-17 00:31:17.371344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6215cc7c36'
down_revision = 'dc4e168b2618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('admin', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('author', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'author')
    op.drop_column('users', 'admin')
    op.drop_column('posts', 'published')
    # ### end Alembic commands ###
