"""empty message

Revision ID: 8f96b90b53c7
Revises: 35f22a6aa623
Create Date: 2022-02-25 16:50:42.646032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f96b90b53c7'
down_revision = '35f22a6aa623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_telegram', table_name='users')
    op.create_index(op.f('ix_users_telegram'), 'users', ['telegram'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram'), table_name='users')
    op.create_index('ix_users_telegram', 'users', ['telegram'], unique=False)
    # ### end Alembic commands ###
